version: 2.1
orbs:
  node: circleci/node@5
  php: circleci/php@1

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
      - store_artifacts:
          path: ./public
          destination: node-build

  test-php:
    docker:
      - image: cimg/php:8.2
      - image: mysql:8.0
        name: mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - run:
          name: composer install 
          command: composer install --no-progress --prefer-dist --optimize-autoloader
      - run: cp .env.testing .env
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in {1..30}; do
              nc -z mysql 3306 && echo "MySQL is up!" && exit 0
              echo "Waiting for MySQL..."
              sleep 2
            done
            echo "MySQL failed to start"
            exit 1
      - run:
          name: Database migration
          command: php artisan migrate --force
      - run:
          name: phpunit tests
          command: ./vendor/bin/phpunit
    

workflows:
  build-and-test:
    jobs:
      - build-node
      - test-php
